name: dicex CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: wulffern/ciceda:ubuntu_0.1.5
      options: --user root
    steps:
      - name: dicex
        uses: actions/checkout@main
      - name: Run programs
        run:  |
          export PATH="/opt/eda/bin:$PATH"
          python3 -m pip install -r requirements.txt
          make test
